Repository PointTils/Backend, pull requests merged in 2025-09, with the labels that each got.

#99 Fix/92 corrigir post de usuário intérprete para que não exija dados profissionais
  pointtils/src/main/java/com/pointtils/pointtils/src/application/controllers/InterpreterController.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/dto/requests/InterpreterBasicRequestDTO.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/mapper/InterpreterResponseMapper.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/services/InterpreterRegisterService.java
  pointtils/src/main/java/com/pointtils/pointtils/src/core/domain/entities/Interpreter.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/InterpreterControllerTest.java
Labels: débito técnico

#103 Feat/US04/User Image To S3
  pointtils/pom.xml
  pointtils/src/main/java/com/pointtils/pointtils/src/application/controllers/UserPicturePatchController.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/dto/requests/UserPicturePatchRequestDTO.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/dto/responses/UserResponseDTO.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/services/S3Service.java
  pointtils/src/main/java/com/pointtils/pointtils/src/application/services/UserPicturePatchService.java
  pointtils/src/test/java/com/pointtils/pointtils/PointtilsApplicationTests.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/AuthControllerTest.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/EnterpriseControllerTest.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/InterpreterControllerTest.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/PersonControllerTest.java
  pointtils/src/test/java/com/pointtils/pointtils/src/application/controllers/StateControllerTest.java
  pointtils/src/test/java/com/pointtils/pointtils/src/infrastructure/configs/JwtRefreshTokenTest.java
  pointtils/src/test/resources/application.properties
Labels: feature

#118 bucketName changed
  pointtils/src/main/java/com/pointtils/pointtils/src/application/services/S3Service.java
Labels: bugfix
